In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df = pd.read_csv("data/diabetic_data.csv")
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [3]:
df.shape

(101766, 50)

In [4]:
df.dtypes

encounter_id                 int64
patient_nbr                  int64
race                        object
gender                      object
age                         object
weight                      object
admission_type_id            int64
discharge_disposition_id     int64
admission_source_id          int64
time_in_hospital             int64
payer_code                  object
medical_specialty           object
num_lab_procedures           int64
num_procedures               int64
num_medications              int64
number_outpatient            int64
number_emergency             int64
number_inpatient             int64
diag_1                      object
diag_2                      object
diag_3                      object
number_diagnoses             int64
max_glu_serum               object
A1Cresult                   object
metformin                   object
repaglinide                 object
nateglinide                 object
chlorpropamide              object
glimepiride                 object
acetohexamide               object
glipizide                   object
glyburide                   object
tolbutamide                 object
pioglitazone                object
rosiglitazone               object
acarbose                    object
miglitol                    object
troglitazone                object
tolazamide                  object
examide                     object
citoglipton                 object
insulin                     object
glyburide-metformin         object
glipizide-metformin         object
glimepiride-pioglitazone    object
metformin-rosiglitazone     object
metformin-pioglitazone      object
change                      object
diabetesMed                 object
readmitted                  object
dtype: object

In [15]:
for col in df.columns:
    if(df[col].dtypes=="object"):
         print(col,df[col][df[col] == '?'].count())

race 2273
gender 0
age 0
weight 98569
payer_code 40256
medical_specialty 49949
diag_1 21
diag_2 358
diag_3 1423
max_glu_serum 0
A1Cresult 0
metformin 0
repaglinide 0
nateglinide 0
chlorpropamide 0
glimepiride 0
acetohexamide 0
glipizide 0
glyburide 0
tolbutamide 0
pioglitazone 0
rosiglitazone 0
acarbose 0
miglitol 0
troglitazone 0
tolazamide 0
examide 0
citoglipton 0
insulin 0
glyburide-metformin 0
glipizide-metformin 0
glimepiride-pioglitazone 0
metformin-rosiglitazone 0
metformin-pioglitazone 0
change 0
diabetesMed 0
readmitted 0

In [6]:
df['diag_1'][df['diag_1'] == '?']

518      ?
1006     ?
1267     ?
1488     ?
3197     ?
7845     ?
14503    ?
19714    ?
32514    ?
37693    ?
49516    ?
56931    ?
57058    ?
57737    ?
60314    ?
61369    ?
61763    ?
66848    ?
86018    ?
87181    ?
98396    ?
Name: diag_1, dtype: object

In [8]:
df.nunique()

encounter_id                101766
patient_nbr                  71518
race                             6
gender                           3
age                             10
weight                          10
admission_type_id                8
discharge_disposition_id        26
admission_source_id             17
time_in_hospital                14
payer_code                      18
medical_specialty               73
num_lab_procedures             118
num_procedures                   7
num_medications                 75
number_outpatient               39
number_emergency                33
number_inpatient                21
diag_1                         717
diag_2                         749
diag_3                         790
number_diagnoses                16
max_glu_serum                    4
A1Cresult                        4
metformin                        4
repaglinide                      4
nateglinide                      4
chlorpropamide                   4
glimepiride                      4
acetohexamide                    2
glipizide                        4
glyburide                        4
tolbutamide                      2
pioglitazone                     4
rosiglitazone                    4
acarbose                         4
miglitol                         4
troglitazone                     2
tolazamide                       3
examide                          1
citoglipton                      1
insulin                          4
glyburide-metformin              4
glipizide-metformin              2
glimepiride-pioglitazone         2
metformin-rosiglitazone          2
metformin-pioglitazone           2
change                           2
diabetesMed                      2
readmitted                       3
dtype: int64

In [17]:
df.patient_nbr.describe()

count    1.017660e+05
mean     5.433040e+07
std      3.869636e+07
min      1.350000e+02
25%      2.341322e+07
50%      4.550514e+07
75%      8.754595e+07
max      1.895026e+08
Name: patient_nbr, dtype: float64

In [18]:
df.groupby('readmitted').size()

readmitted
<30    11357
>30    35545
NO     54864
dtype: int64

In [19]:
df.groupby('gender').size()

gender
Female             54708
Male               47055
Unknown/Invalid        3
dtype: int64

In [20]:
df.groupby('age').size()

age
[0-10)        161
[10-20)       691
[20-30)      1657
[30-40)      3775
[40-50)      9685
[50-60)     17256
[60-70)     22483
[70-80)     26068
[80-90)     17197
[90-100)     2793
dtype: int64

In [22]:
df1 = df.drop(['weight','payer_code','medical_specialty'], axis = 1)

In [23]:
df1.nunique()

encounter_id                101766
patient_nbr                  71518
race                             6
gender                           3
age                             10
admission_type_id                8
discharge_disposition_id        26
admission_source_id             17
time_in_hospital                14
num_lab_procedures             118
num_procedures                   7
num_medications                 75
number_outpatient               39
number_emergency                33
number_inpatient                21
diag_1                         717
diag_2                         749
diag_3                         790
number_diagnoses                16
max_glu_serum                    4
A1Cresult                        4
metformin                        4
repaglinide                      4
nateglinide                      4
chlorpropamide                   4
glimepiride                      4
acetohexamide                    2
glipizide                        4
glyburide                        4
tolbutamide                      2
pioglitazone                     4
rosiglitazone                    4
acarbose                         4
miglitol                         4
troglitazone                     2
tolazamide                       3
examide                          1
citoglipton                      1
insulin                          4
glyburide-metformin              4
glipizide-metformin              2
glimepiride-pioglitazone         2
metformin-rosiglitazone          2
metformin-pioglitazone           2
change                           2
diabetesMed                      2
readmitted                       3
dtype: int64

In [24]:
df1 = df1.drop(['examide','citoglipton'], axis=1)

In [25]:
df1.groupby('admission_type_id').size()

admission_type_id
1    53990
2    18480
3    18869
4       10
5     4785
6     5291
7       21
8      320
dtype: int64

In [26]:

df1.admission_type_id.replace(
list(range(1,9)),['Emergency',
'Urgent',
'Elective',
'Newborn',
'Not Available',
'NULL',
'Trauma Center',
'Not Mapped'], inplace=True)

In [27]:
df1.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,tolazamide,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),NULL,25,1,1,41,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),Emergency,1,7,3,59,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),Emergency,1,7,2,11,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),Emergency,1,7,2,44,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),Emergency,1,7,1,51,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [28]:
id_list = ['Physician Referral',
'Clinic Referral',
'HMO Referral',
'Transfer from a hospital',
'Transfer from a Skilled Nursing Facility (SNF)',
'Transfer from another health care facility',
'Emergency Room',
'Court/Law Enforcement',
'Not Available',
'Transfer from critial access hospital',
'Normal Delivery',
'Premature Delivery',
'Sick Baby',
'Extramural Birth',
'Not Available',
'NULL',
'Transfer From Another Home Health Agency',
'Readmission to Same Home Health Agency',
'Not Mapped',
'Unknown/Invalid',
'Transfer from hospital inpt/same fac reslt in a sep claim',
'Born inside this hospital',
'Born outside this hospital',
'Transfer from Ambulatory Surgery Center',
'Transfer from Hospice']

df1.admission_source_id.replace(list(range(1,len(id_list)+1)),id_list, inplace=True)

In [29]:
df1.groupby('admission_source_id').size()

admission_source_id
Born inside this hospital                            12
Clinic Referral                                    1104
Court/Law Enforcement                                16
Emergency Room                                    57494
Extramural Birth                                      2
HMO Referral                                        187
Normal Delivery                                       2
Not Available                                       125
Physician Referral                                29565
Sick Baby                                             1
Transfer From Another Home Health Agency           6781
Transfer from Hospice                                 2
Transfer from a Skilled Nursing Facility (SNF)      855
Transfer from a hospital                           3187
Transfer from another health care facility         2264
Transfer from critial access hospital                 8
Unknown/Invalid                                     161
dtype: int64

In [30]:
id_list = ['Discharged to home',
'Discharged/transferred to another short term hospital',
'Discharged/transferred to SNF',
'Discharged/transferred to ICF',
'Discharged/transferred to another type of inpatient care institution',
'Discharged/transferred to home with home health service',
'Left AMA',
'Discharged/transferred to home under care of Home IV provider',
'Admitted as an inpatient to this hospital',
'Neonate discharged to another hospital for neonatal aftercare',
'Expired',
'Still patient or expected to return for outpatient services',
'Hospice / home',
'Hospice / medical facility',
'Discharged/transferred within this institution to Medicare approved swing bed',
'Discharged/transferred/referred another institution for outpatient services',
'Discharged/transferred/referred to this institution for outpatient services',
'NULL',
'Expired at home. Medicaid only, hospice.',
'Expired in a medical facility. Medicaid only, hospice.',
'Expired, place unknown. Medicaid only, hospice.',
'Discharged/transferred to another rehab fac including rehab units of a hospital .',
'Discharged/transferred to a long term care hospital.',
'Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.',
'Not Mapped',
'Unknown/Invalid',
'Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere',
'Discharged/transferred to a federal health care facility.',
'Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital',
'Discharged/transferred to a Critical Access Hospital (CAH).']

df1.discharge_disposition_id.replace(list(range(1,len(id_list)+1)),id_list, inplace=True)
df1.discharge_disposition_id.head()

0            Not Mapped
1    Discharged to home
2    Discharged to home
3    Discharged to home
4    Discharged to home
Name: discharge_disposition_id, dtype: object

In [31]:
df1 = df1[df1.discharge_disposition_id.str.contains("Expired") == False]

In [32]:
df1 = df1[df1.discharge_disposition_id.str.contains("Hospice") == False]

In [33]:
numeric_code_ranges = [(1,139),
(140,239),
(240,279),
(280,289),
(290,319),
(320,389),
(390,459),
(460,519),
(520,579),
(580,629),
(630,677),
(680,709),
(710,739),
(740,759),  
(760,779),  
(780,799),  
(800,999)]

numeric_code_ranges

[(1, 139),
 (140, 239),
 (240, 279),
 (280, 289),
 (290, 319),
 (320, 389),
 (390, 459),
 (460, 519),
 (520, 579),
 (580, 629),
 (630, 677),
 (680, 709),
 (710, 739),
 (740, 759),
 (760, 779),
 (780, 799),
 (800, 999)]

In [34]:
ICD9_diagnosis_groups = ['Infectious And Parasitic Diseases',
'Neoplasms',
'Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders',
'Diseases Of The Blood And Blood-Forming Organs',
'Mental Disorders',
'Diseases Of The Nervous System And Sense Organs',
'Diseases Of The Circulatory System',
'Diseases Of The Respiratory System',
'Diseases Of The Digestive System',
'Diseases Of The Genitourinary System',
'Complications Of Pregnancy, Childbirth, And The Puerperium',
'Diseases Of The Skin And Subcutaneous Tissue',
'Diseases Of The Musculoskeletal System And Connective Tissue',
'Congential Anomalies',
'Certain Conditions Originating In The Perinatal Period',
'Symptoms, Signs, And Ill-Defined Conditions',
'Injury And Poisoning']
ICD9_diagnosis_groups

['Infectious And Parasitic Diseases',
 'Neoplasms',
 'Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders',
 'Diseases Of The Blood And Blood-Forming Organs',
 'Mental Disorders',
 'Diseases Of The Nervous System And Sense Organs',
 'Diseases Of The Circulatory System',
 'Diseases Of The Respiratory System',
 'Diseases Of The Digestive System',
 'Diseases Of The Genitourinary System',
 'Complications Of Pregnancy, Childbirth, And The Puerperium',
 'Diseases Of The Skin And Subcutaneous Tissue',
 'Diseases Of The Musculoskeletal System And Connective Tissue',
 'Congential Anomalies',
 'Certain Conditions Originating In The Perinatal Period',
 'Symptoms, Signs, And Ill-Defined Conditions',
 'Injury And Poisoning']

In [35]:
codes = zip(numeric_code_ranges, ICD9_diagnosis_groups)
codeSet = set(codes)
codeSet

{((1, 139), 'Infectious And Parasitic Diseases'),
 ((140, 239), 'Neoplasms'),
 ((240, 279),
  'Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders'),
 ((280, 289), 'Diseases Of The Blood And Blood-Forming Organs'),
 ((290, 319), 'Mental Disorders'),
 ((320, 389), 'Diseases Of The Nervous System And Sense Organs'),
 ((390, 459), 'Diseases Of The Circulatory System'),
 ((460, 519), 'Diseases Of The Respiratory System'),
 ((520, 579), 'Diseases Of The Digestive System'),
 ((580, 629), 'Diseases Of The Genitourinary System'),
 ((630, 677), 'Complications Of Pregnancy, Childbirth, And The Puerperium'),
 ((680, 709), 'Diseases Of The Skin And Subcutaneous Tissue'),
 ((710, 739), 'Diseases Of The Musculoskeletal System And Connective Tissue'),
 ((740, 759), 'Congential Anomalies'),
 ((760, 779), 'Certain Conditions Originating In The Perinatal Period'),
 ((780, 799), 'Symptoms, Signs, And Ill-Defined Conditions'),
 ((800, 999), 'Injury And Poisoning')}

In [36]:
df_icd = df1.copy()
for num_range, diagnosis in codeSet:
    #print(num_range)
    oldlist = range(num_range[0],num_range[1]+1)
    oldlist = [str(x) for x in oldlist]
    newlist = [diagnosis] * len(oldlist)
    for curr_col in ['diag_1', 'diag_2', 'diag_3']:
        df_icd[curr_col].replace(oldlist, newlist, inplace=True)

In [37]:
for curr_col in ['diag_1', 'diag_2', 'diag_3']:
    df_icd[curr_col].replace(oldlist, newlist, inplace=True)
    df_icd.loc[df_icd[curr_col].str.contains('V'), curr_col] = 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'

In [38]:
for curr_col in ['diag_1', 'diag_2', 'diag_3']:
    df_icd[curr_col].replace(oldlist, newlist, inplace=True)
    df_icd.loc[df_icd[curr_col].str.contains('E'), curr_col] = 'Supplementary Classification Of External Causes Of Injury And Poisoning'

In [39]:
for curr_col in ['diag_1', 'diag_2', 'diag_3']:
    df_icd[curr_col].replace(oldlist, newlist, inplace=True)
    df_icd.loc[df_icd[curr_col].str.contains('250'), curr_col] ='Diabetes mellitus'

In [40]:
print(df_icd['diag_1'].unique())

['Diabetes mellitus'
 'Supplementary Classification Of External Causes Of Injury And Poisoning'
 'Complications Of Pregnancy, Childbirth, And The Puerperium'
 'Infectious And Parasitic Diseases' 'Neoplasms'
 'Diseases Of The Circulatory System' 'Diseases Of The Respiratory System'
 'Injury And Poisoning' 'Diseases Of The Skin And Subcutaneous Tissue'
 'Diseases Of The Musculoskeletal System And Connective Tissue'
 'Diseases Of The Digestive System'
 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'
 'Symptoms, Signs, And Ill-Defined Conditions'
 'Diseases Of The Genitourinary System' 'Mental Disorders'
 'Diseases Of The Nervous System And Sense Organs'
 'Diseases Of The Blood And Blood-Forming Organs' '?'
 'Congential Anomalies']

In [41]:
df_icd['OUTPUT_LABEL'] = (df_icd.readmitted == '<30').astype('int')
df_icd['OUTPUT_LABEL']

0         0
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        1
12        1
13        0
14        0
15        0
16        1
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
         ..
101735    0
101736    0
101737    0
101738    0
101739    0
101740    0
101741    0
101742    0
101744    0
101745    0
101746    1
101747    0
101748    0
101749    0
101750    1
101751    0
101752    0
101753    0
101754    0
101755    0
101756    0
101757    0
101758    0
101759    0
101760    0
101761    0
101762    0
101763    0
101764    0
101765    0
Name: OUTPUT_LABEL, Length: 99343, dtype: int32

In [42]:
def calc_prevalence(y_actual):
    return (sum(y_actual)/len(y_actual))
print('Prevalence:%.3f'%calc_prevalence(df_icd['OUTPUT_LABEL'].values))

Prevalence:0.114

In [43]:
for c in list(df_icd.columns):
    
    # get a list of unique values
    n = df_icd[c].unique()
    
    # if number of unique values is less than 30, print the values. Otherwise print the number of unique values
    if len(n)<30:
        print(c)
        print(n)
    else:
        print(c + ': ' +str(len(n)) + ' unique values')

encounter_id: 99343 unique values
patient_nbr: 69990 unique values
race
['Caucasian' 'AfricanAmerican' '?' 'Other' 'Asian' 'Hispanic']
gender
['Female' 'Male' 'Unknown/Invalid']
age
['[0-10)' '[10-20)' '[20-30)' '[30-40)' '[40-50)' '[50-60)' '[60-70)'
 '[70-80)' '[80-90)' '[90-100)']
admission_type_id
['NULL' 'Emergency' 'Urgent' 'Elective' 'Newborn' 'Not Available'
 'Not Mapped' 'Trauma Center']
discharge_disposition_id
['Not Mapped' 'Discharged to home' 'Discharged/transferred to SNF'
 'Discharged/transferred to home with home health service'
 'Discharged/transferred to another short term hospital'
 'Discharged/transferred to another type of inpatient care institution'
 'Left AMA'
 'Neonate discharged to another hospital for neonatal aftercare'
 'Discharged/transferred to ICF' 'NULL'
 'Discharged/transferred to home under care of Home IV provider'
 'Still patient or expected to return for outpatient services'
 'Discharged/transferred/referred another institution for outpatient services'
 'Discharged/transferred/referred to this institution for outpatient services'
 'Discharged/transferred to another rehab fac including rehab units of a hospital .'
 'Discharged/transferred to a long term care hospital.'
 'Admitted as an inpatient to this hospital'
 'Discharged/transferred within this institution to Medicare approved swing bed'
 'Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.'
 'Discharged/transferred to a federal health care facility.'
 'Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere']
admission_source_id
['Physician Referral' 'Emergency Room' 'Clinic Referral'
 'Transfer from a hospital'
 'Transfer from a Skilled Nursing Facility (SNF)' 'Unknown/Invalid'
 'Transfer from another health care facility' 'HMO Referral'
 'Transfer From Another Home Health Agency' 'Court/Law Enforcement'
 'Not Available' 'Extramural Birth'
 'Transfer from critial access hospital' 'Born inside this hospital'
 'Normal Delivery' 'Transfer from Hospice' 'Sick Baby']
time_in_hospital
[ 1  3  2  4  5 13 12  9  7 10  6 11  8 14]
num_lab_procedures: 118 unique values
num_procedures
[0 5 1 6 2 3 4]
num_medications: 75 unique values
number_outpatient: 39 unique values
number_emergency: 33 unique values
number_inpatient
[ 0  1  2  3  6  5  4  7  9  8 15 10 11 14 12 13 17 16 21 18 19]
diag_1
['Diabetes mellitus'
 'Supplementary Classification Of External Causes Of Injury And Poisoning'
 'Complications Of Pregnancy, Childbirth, And The Puerperium'
 'Infectious And Parasitic Diseases' 'Neoplasms'
 'Diseases Of The Circulatory System' 'Diseases Of The Respiratory System'
 'Injury And Poisoning' 'Diseases Of The Skin And Subcutaneous Tissue'
 'Diseases Of The Musculoskeletal System And Connective Tissue'
 'Diseases Of The Digestive System'
 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'
 'Symptoms, Signs, And Ill-Defined Conditions'
 'Diseases Of The Genitourinary System' 'Mental Disorders'
 'Diseases Of The Nervous System And Sense Organs'
 'Diseases Of The Blood And Blood-Forming Organs' '?'
 'Congential Anomalies']
diag_2
['?' 'Diabetes mellitus'
 'Supplementary Classification Of External Causes Of Injury And Poisoning'
 'Neoplasms' 'Diseases Of The Circulatory System'
 'Diseases Of The Respiratory System'
 'Diseases Of The Blood And Blood-Forming Organs' 'Injury And Poisoning'
 'Diseases Of The Musculoskeletal System And Connective Tissue'
 'Diseases Of The Genitourinary System'
 'Infectious And Parasitic Diseases' 'Diseases Of The Digestive System'
 'Diseases Of The Skin And Subcutaneous Tissue'
 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'
 'Diseases Of The Nervous System And Sense Organs'
 'Symptoms, Signs, And Ill-Defined Conditions' 'Mental Disorders'
 'Complications Of Pregnancy, Childbirth, And The Puerperium'
 'Congential Anomalies']
diag_3
['?'
 'Supplementary Classification Of External Causes Of Injury And Poisoning'
 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'
 'Diseases Of The Circulatory System' 'Infectious And Parasitic Diseases'
 'Diseases Of The Respiratory System' 'Injury And Poisoning' 'Neoplasms'
 'Diabetes mellitus' 'Diseases Of The Genitourinary System'
 'Diseases Of The Musculoskeletal System And Connective Tissue'
 'Symptoms, Signs, And Ill-Defined Conditions'
 'Diseases Of The Digestive System'
 'Diseases Of The Skin And Subcutaneous Tissue' 'Mental Disorders'
 'Congential Anomalies' 'Diseases Of The Nervous System And Sense Organs'
 'Complications Of Pregnancy, Childbirth, And The Puerperium'
 'Diseases Of The Blood And Blood-Forming Organs' '365.44']
number_diagnoses
[ 1  9  6  7  5  8  3  4  2 16 12 13 15 10 11 14]
max_glu_serum
['None' '>300' 'Norm' '>200']
A1Cresult
['None' '>7' '>8' 'Norm']
metformin
['No' 'Steady' 'Up' 'Down']
repaglinide
['No' 'Up' 'Steady' 'Down']
nateglinide
['No' 'Steady' 'Down' 'Up']
chlorpropamide
['No' 'Steady' 'Down' 'Up']
glimepiride
['No' 'Steady' 'Down' 'Up']
acetohexamide
['No' 'Steady']
glipizide
['No' 'Steady' 'Up' 'Down']
glyburide
['No' 'Steady' 'Up' 'Down']
tolbutamide
['No' 'Steady']
pioglitazone
['No' 'Steady' 'Up' 'Down']
rosiglitazone
['No' 'Steady' 'Up' 'Down']
acarbose
['No' 'Steady' 'Up' 'Down']
miglitol
['No' 'Steady' 'Down' 'Up']
troglitazone
['No' 'Steady']
tolazamide
['No' 'Steady' 'Up']
insulin
['No' 'Up' 'Steady' 'Down']
glyburide-metformin
['No' 'Steady' 'Down' 'Up']
glipizide-metformin
['No' 'Steady']
glimepiride-pioglitazone
['No' 'Steady']
metformin-rosiglitazone
['No' 'Steady']
metformin-pioglitazone
['No' 'Steady']
change
['No' 'Ch']
diabetesMed
['No' 'Yes']
readmitted
['NO' '>30' '<30']
OUTPUT_LABEL
[0 1]

In [44]:
df_icd = df_icd.replace('?',np.nan)

In [45]:
df_icd[df_icd.columns].isnull().sum()

encounter_id                   0
patient_nbr                    0
race                        2234
gender                         0
age                            0
admission_type_id              0
discharge_disposition_id       0
admission_source_id            0
time_in_hospital               0
num_lab_procedures             0
num_procedures                 0
num_medications                0
number_outpatient              0
number_emergency               0
number_inpatient               0
diag_1                        20
diag_2                       356
diag_3                      1419
number_diagnoses               0
max_glu_serum                  0
A1Cresult                      0
metformin                      0
repaglinide                    0
nateglinide                    0
chlorpropamide                 0
glimepiride                    0
acetohexamide                  0
glipizide                      0
glyburide                      0
tolbutamide                    0
pioglitazone                   0
rosiglitazone                  0
acarbose                       0
miglitol                       0
troglitazone                   0
tolazamide                     0
insulin                        0
glyburide-metformin            0
glipizide-metformin            0
glimepiride-pioglitazone       0
metformin-rosiglitazone        0
metformin-pioglitazone         0
change                         0
diabetesMed                    0
readmitted                     0
OUTPUT_LABEL                   0
dtype: int64

In [46]:
cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']
df_icd[cols_num].isnull().sum()

time_in_hospital      0
num_lab_procedures    0
num_procedures        0
num_medications       0
number_outpatient     0
number_emergency      0
number_inpatient      0
number_diagnoses      0
dtype: int64

In [47]:
df_icd['race'] = df_icd['race'].fillna('RACE')

In [49]:
for col in df_icd.columns:
    if(df_icd[col].dtypes=="object"):
         print(col,df_icd[col][df_icd[col] == '?'].count())

race 0
gender 0
age 0
admission_type_id 0
discharge_disposition_id 0
admission_source_id 0
diag_1 0
diag_2 0
diag_3 0
max_glu_serum 0
A1Cresult 0
metformin 0
repaglinide 0
nateglinide 0
chlorpropamide 0
glimepiride 0
acetohexamide 0
glipizide 0
glyburide 0
tolbutamide 0
pioglitazone 0
rosiglitazone 0
acarbose 0
miglitol 0
troglitazone 0
tolazamide 0
insulin 0
glyburide-metformin 0
glipizide-metformin 0
glimepiride-pioglitazone 0
metformin-rosiglitazone 0
metformin-pioglitazone 0
change 0
diabetesMed 0
readmitted 0

In [50]:
cols_cat = ['race', 'gender', 
       'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed','admission_type_id',
        'discharge_disposition_id', 'admission_source_id']

In [51]:

df_cat = pd.get_dummies(df_icd[cols_cat],drop_first = True)

In [52]:
df_cat[1:20].head()

,race_Asian,race_Caucasian,race_Hispanic,race_Other,race_RACE,gender_Male,gender_Unknown/Invalid,max_glu_serum_>300,max_glu_serum_None,max_glu_serum_Norm,...,admission_source_id_Not Available,admission_source_id_Physician Referral,admission_source_id_Sick Baby,admission_source_id_Transfer From Another Home Health Agency,admission_source_id_Transfer from Hospice,admission_source_id_Transfer from a Skilled Nursing Facility (SNF),admission_source_id_Transfer from a hospital,admission_source_id_Transfer from another health care facility,admission_source_id_Transfer from critial access hospital,admission_source_id_Unknown/Invalid
1,0,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
4,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
5,0,1,0,0,0,1,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [53]:
df_icd = pd.concat([df_icd,df_cat], axis = 1)

In [54]:

cols_all_cat = list(df_cat.columns)

In [55]:
age_id = {'[0-10)':0, 
          '[10-20)':10, 
          '[20-30)':20, 
          '[30-40)':30, 
          '[40-50)':40, 
          '[50-60)':50,
          '[60-70)':60, 
          '[70-80)':70, 
          '[80-90)':80, 
          '[90-100)':90}
df_icd['age_group'] = df_icd.age.replace(age_id)
cols_extra = ['age_group']

In [56]:
df_icd.head()

,encounter_id,patient_nbr,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,...,admission_source_id_Physician Referral,admission_source_id_Sick Baby,admission_source_id_Transfer From Another Home Health Agency,admission_source_id_Transfer from Hospice,admission_source_id_Transfer from a Skilled Nursing Facility (SNF),admission_source_id_Transfer from a hospital,admission_source_id_Transfer from another health care facility,admission_source_id_Transfer from critial access hospital,admission_source_id_Unknown/Invalid,age_group
0,2278392,8222157,Caucasian,Female,[0-10),NULL,Not Mapped,Physician Referral,1,41,...,1,0,0,0,0,0,0,0,0,0
1,149190,55629189,Caucasian,Female,[10-20),Emergency,Discharged to home,Emergency Room,3,59,...,0,0,0,0,0,0,0,0,0,10
2,64410,86047875,AfricanAmerican,Female,[20-30),Emergency,Discharged to home,Emergency Room,2,11,...,0,0,0,0,0,0,0,0,0,20
3,500364,82442376,Caucasian,Male,[30-40),Emergency,Discharged to home,Emergency Room,2,44,...,0,0,0,0,0,0,0,0,0,30
4,16680,42519267,Caucasian,Male,[40-50),Emergency,Discharged to home,Emergency Room,1,51,...,0,0,0,0,0,0,0,0,0,40

In [57]:
print('Total number of features:', len(cols_num + cols_all_cat + cols_extra))
print('Numerical Features:',len(cols_num))
print('Categorical Features:',len(cols_all_cat))
print('Extra features:',len(cols_extra))

Total number of features: 115
Numerical Features: 8
Categorical Features: 106
Extra features: 1

In [58]:
df_icd[cols_num + cols_all_cat + cols_extra].isnull().sum().sort_values(ascending = False).head(10)

age_group                0
nateglinide_Steady       0
chlorpropamide_No        0
chlorpropamide_Steady    0
chlorpropamide_Up        0
glimepiride_No           0
glimepiride_Steady       0
glimepiride_Up           0
acetohexamide_Steady     0
glipizide_No             0
dtype: int64

In [59]:
col2 = cols_num + cols_all_cat + cols_extra
df_data = df_icd[col2 + ['OUTPUT_LABEL']]

In [60]:
df_valid=df_data.sample(frac=0.30,random_state=42)
print('Split size: %.3f'%(len(df_valid)/len(df_data)))

Split size: 0.300

In [61]:
df_test = df_valid.sample(frac = 0.5, random_state = 42)
df_valid1 = df_valid.drop(df_test.index)

In [62]:
df_train=df_data.drop(df_valid.index)

In [63]:

print('Test prevalence(n = %d):%.3f'%(len(df_test),calc_prevalence(df_test.OUTPUT_LABEL.values)))
print('Valid prevalence(n = %d):%.3f'%(len(df_valid1),calc_prevalence(df_valid1.OUTPUT_LABEL.values)))
print('Train all prevalence(n = %d):%.3f'%(len(df_train), calc_prevalence(df_train.OUTPUT_LABEL.values)))

Test prevalence(n = 14902):0.116
Valid prevalence(n = 14901):0.115
Train all prevalence(n = 69540):0.113

In [64]:

X_train = df_train[col2].values
X_valid = df_valid1[col2].values

y_train = df_train['OUTPUT_LABEL'].values
y_valid = df_valid1['OUTPUT_LABEL'].values

In [65]:

from sklearn.metrics import roc_auc_score, accuracy_score, precision_score, recall_score
def calc_specificity(y_actual, y_pred, thresh):
    # calculates specificity
    return sum((y_pred < thresh) & (y_actual == 0)) /sum(y_actual ==0)

def print_report(y_actual, y_pred, thresh):
    
    auc = roc_auc_score(y_actual, y_pred)
    accuracy = accuracy_score(y_actual, (y_pred > thresh))
    recall = recall_score(y_actual, (y_pred > thresh))
    precision = precision_score(y_actual, (y_pred > thresh))
    specificity = calc_specificity(y_actual, y_pred, thresh)
    print('AUC:%.3f'%auc)
    print('accuracy:%.3f'%accuracy)
    print('recall:%.3f'%recall)
    print('precision:%.3f'%precision)
    print('specificity:%.3f'%specificity)
    print('prevalence:%.3f'%calc_prevalence(y_actual))
    print(' ')
    return auc, accuracy, recall, precision, specificity

In [66]:
thresh = 0.5

In [67]:

from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(max_depth = 10, random_state = 42)
tree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=42,
            splitter='best')

In [ ]:
import pickle
with open('tree.pkl', 'wb') as file:
pickle.dump(tree, file)

In [68]:

y_train_preds = tree.predict_proba(X_train)[:,1]
y_valid_preds = tree.predict_proba(X_valid)[:,1]

print('Decision Tree')
print('Training:')
tree_train_auc, tree_train_accuracy, tree_train_recall, tree_train_precision, tree_train_specificity =print_report(y_train,y_train_preds, thresh)
print('Validation:')
tree_valid_auc, tree_valid_accuracy, tree_valid_recall, tree_valid_precision, tree_valid_specificity = print_report(y_valid,y_valid_preds, thresh)

Decision Tree
Training:
AUC:0.690
accuracy:0.895
recall:0.086
precision:0.836
specificity:0.997
prevalence:0.113

Validation:
AUC:0.628
accuracy:0.881
recall:0.041
precision:0.351
specificity:0.989
prevalence:0.115

In [80]:
df_s = pd.read_csv('result.csv')
print(df_s.head())

   encounter_id  patient_nbr       race  gender     age weight  \
0       2278392      8222157  Caucasian  Female  [0-10)      ?

   admission_type_id  discharge_disposition_id  admission_source_id  \
0                  6                        25                    1

   time_in_hospital     ...     examide citoglipton  insulin  \
0                 1     ...          No          No       No

   glyburide-metformin  glipizide-metformin  glimepiride-pioglitazone  \
0                   No                   No                        No

   metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed
0                       No                      No      No          No

[1 rows x 49 columns]

In [94]:
def preprocess(df):
    df1 = df.drop(['weight','payer_code','medical_specialty'], axis = 1)
    df1 = df1.drop(['examide','citoglipton'], axis=1)
    df.admission_type_id.replace(
    list(range(1,9)),['Emergency',
    'Urgent',
    'Elective',
    'Newborn',
    'Not Available',
    'NULL',
    'Trauma Center',
    'Not Mapped'], inplace=True)
    id_list = ['Physician Referral',
    'Clinic Referral',
    'HMO Referral',
    'Transfer from a hospital',
    'Transfer from a Skilled Nursing Facility (SNF)',
    'Transfer from another health care facility',
    'Emergency Room',
    'Court/Law Enforcement',
    'Not Available',
    'Transfer from critial access hospital',
    'Normal Delivery',
    'Premature Delivery',
    'Sick Baby',
    'Extramural Birth',
    'Not Available',
    'NULL',
    'Transfer From Another Home Health Agency',
    'Readmission to Same Home Health Agency',
    'Not Mapped',
    'Unknown/Invalid',
    'Transfer from hospital inpt/same fac reslt in a sep claim',
    'Born inside this hospital',
    'Born outside this hospital',
    'Transfer from Ambulatory Surgery Center',
    'Transfer from Hospice']

    df1.admission_source_id.replace(list(range(1,len(id_list)+1)),id_list, inplace=True)
    id_list = ['Discharged to home','Discharged/transferred to another short term hospital','Discharged/transferred to SNF',
    'Discharged/transferred to ICF','Discharged/transferred to another type of inpatient care institution',
    'Discharged/transferred to home with home health service','Left AMA','Discharged/transferred to home under care of Home IV provider',
    'Admitted as an inpatient to this hospital',
    'Neonate discharged to another hospital for neonatal aftercare',
    'Expired',
    'Still patient or expected to return for outpatient services',
    'Hospice / home',
    'Hospice / medical facility',
    'Discharged/transferred within this institution to Medicare approved swing bed',
    'Discharged/transferred/referred another institution for outpatient services',
    'Discharged/transferred/referred to this institution for outpatient services',
    'NULL',
    'Expired at home. Medicaid only, hospice.',
    'Expired in a medical facility. Medicaid only, hospice.',
    'Expired, place unknown. Medicaid only, hospice.',
    'Discharged/transferred to another rehab fac including rehab units of a hospital .',
    'Discharged/transferred to a long term care hospital.',
    'Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.',
    'Not Mapped',
    'Unknown/Invalid',
    'Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere',
    'Discharged/transferred to a federal health care facility.',
    'Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital',
    'Discharged/transferred to a Critical Access Hospital (CAH).']

    df1.discharge_disposition_id.replace(list(range(1,len(id_list)+1)),id_list, inplace=True)
    df1 = df1[df1.discharge_disposition_id.str.contains("Expired") == False]
    df1 = df1[df1.discharge_disposition_id.str.contains("Hospice") == False]
    numeric_code_ranges = [(1,139),(140,239),(240,279),(280,289),(290,319),(320,389),(390,459),(460,519),(520,579),(580,629),
    (630,677),(680,709),(710,739),(740,759),  (760,779),  (780,799),(800,999)]
    ICD9_diagnosis_groups = ['Infectious And Parasitic Diseases',
    'Neoplasms',
    'Endocrine, Nutritional And Metabolic Diseases, And Immunity Disorders',
    'Diseases Of The Blood And Blood-Forming Organs',
    'Mental Disorders',
    'Diseases Of The Nervous System And Sense Organs',
    'Diseases Of The Circulatory System',
    'Diseases Of The Respiratory System',
    'Diseases Of The Digestive System',
    'Diseases Of The Genitourinary System',
    'Complications Of Pregnancy, Childbirth, And The Puerperium',
    'Diseases Of The Skin And Subcutaneous Tissue',
    'Diseases Of The Musculoskeletal System And Connective Tissue',
    'Congential Anomalies',
    'Certain Conditions Originating In The Perinatal Period',
    'Symptoms, Signs, And Ill-Defined Conditions',
    'Injury And Poisoning']
    codes = zip(numeric_code_ranges, ICD9_diagnosis_groups)
    codeSet = set(codes)
    df_icd = df1.copy()
    for num_range, diagnosis in codeSet:
        #print(num_range)
        oldlist = range(num_range[0],num_range[1]+1)
        oldlist = [x for x in oldlist]
        newlist = [diagnosis] * len(oldlist)
        for curr_col in ['diag_1', 'diag_2', 'diag_3']:
            df_icd[curr_col].replace(oldlist, newlist, inplace=True)
            print(df_icd[curr_col])
    for curr_col in ['diag_1', 'diag_2', 'diag_3']:
        df_icd[curr_col].replace(oldlist, newlist, inplace=True)
        df_icd.loc[df_icd[curr_col].str.contains('V'), curr_col] = 'Supplementary Classification Of Factors Influencing Health Status And Contact With Health Services'
    for curr_col in ['diag_1', 'diag_2', 'diag_3']:
        df_icd[curr_col].replace(oldlist, newlist, inplace=True)
        df_icd.loc[df_icd[curr_col].str.contains('E'), curr_col] = 'Supplementary Classification Of External Causes Of Injury And Poisoning'
    for curr_col in ['diag_1', 'diag_2', 'diag_3']:
        df_icd[curr_col].replace(oldlist, newlist, inplace=True)
        df_icd.loc[df_icd[curr_col].str.contains('250'), curr_col] ='Diabetes mellitus'
    df_icd = df_icd.replace('?',np.nan)
    cols_num = ['time_in_hospital','num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient','number_diagnoses']
    df_icd['race'] = df_icd['race'].fillna('RACE')
    cols_cat = ['race', 'gender', 
       'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed','admission_type_id',
        'discharge_disposition_id', 'admission_source_id']
    df_cat = pd.get_dummies(df_icd[cols_cat],drop_first = True)
    df_icd = pd.concat([df_icd,df_cat], axis = 1)
    age_id = {'[0-10)':0, 
          '[10-20)':10, 
          '[20-30)':20, 
          '[30-40)':30, 
          '[40-50)':40, 
          '[50-60)':50,
          '[60-70)':60, 
          '[70-80)':70, 
          '[80-90)':80, 
          '[90-100)':90}
    df_icd['age_group'] = df_icd.age.replace(age_id)
    cols_extra = ['age_group']
    col2 = cols_num + cols_all_cat + cols_extra
    df_data = df_icd[col2]
    return df_data

In [95]:
print(preprocess(df_s))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[280, 281, 282, 283, 284, 285, 286, 287, 288, 289]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object
[140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239]
0    250.83
Name: diag_1, dtype: float64
0    ?
Name: diag_2, dtype: object
0    ?
Name: diag_3, dtype: object

AttributeError: Can only use .str accessor with string values, which use np.object_ dtype in pandas

In [ ]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression(random_state = 42)
lr.fit(X_train, y_train)

In [ ]:

y_train_preds = lr.predict_proba(X_train)[:,1]
y_valid_preds = lr.predict_proba(X_valid)[:,1]

print('Logistic Regression')
print('Training:')
lr_train_auc, lr_train_accuracy, lr_train_recall, \
    lr_train_precision, lr_train_specificity = print_report(y_train,y_train_preds, thresh)
print('Validation:')
lr_valid_auc, lr_valid_accuracy, lr_valid_recall, \
    lr_valid_precision, lr_valid_specificity = print_report(y_valid,y_valid_preds, thresh)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(max_depth = 6, random_state = 42)
rf.fit(X_train, y_train)

In [ ]:

y_train_preds = rf.predict_proba(X_train)[:,1]
y_valid_preds = rf.predict_proba(X_valid)[:,1]

print('Random Forest')
print('Training:')
rf_train_auc, rf_train_accuracy, rf_train_recall, rf_train_precision, rf_train_specificity =print_report(y_train,y_train_preds, 0.25)
print('Validation:')
rf_valid_auc, rf_valid_accuracy, rf_valid_recall, rf_valid_precision, rf_valid_specificity = print_report(y_valid,y_valid_preds, 0.25)

In [ ]:
from sklearn.svm import SVC
sv = SVC(kernel = 'sigmoid')
sv.fit(X_train,y_train)

In [ ]:
y_train_preds = sv.predict(X_train)
y_valid_preds = sv.predict(X_valid)

print('Support Vector Machine')
print('Training:')
rf_train_auc, rf_train_accuracy, rf_train_recall, rf_train_precision, rf_train_specificity =print_report(y_train,y_train_preds, 0.25)
print('Validation:')
rf_valid_auc, rf_valid_accuracy, rf_valid_recall, rf_valid_precision, rf_valid_specificity = print_report(y_valid,y_valid_preds, 0.25)